---
output: html_document
editor_options: 
  chunk_output_type: console
---

{{< include _setup.qmd >}}

# PMT model and revenue options

```{r}
#| label: payroll-cutpoints
#| output: false

# define payroll cuts and labels
payroll_cuts <- c(0, 500e3, seq(1e6, 2e6, 200e3), seq(2e6, 5e6, 1e6), Inf, 1.25e6, 1.75e6) |> unique() |> sort()
paygroup_labels <- cutlabs(payroll_cuts)

```

```{r}
#| label: functions
#| output: false

pmtdb_forecast <- function(prob, pmtdb){
  pmtfc <- pmtdb |> 
    mutate(year = prob$year,
         gemp = gemp * (1 + prob$emp_growth),
         gpayroll = gpayroll * (1 + prob$avg_wagerate_growth) * (1 + prob$emp_growth)) |> 
  # get per- variables
  mutate(get_pervars(gfirms, gestabs, gemp, gpayroll))
  
  return(pmtfc)
}

tax2024 <- list(
  shortname = "tax2024",
  exempt = expression(
      owner == "Federal Government" |
        (owner == "Local Government") & naics=="6111"),
  excluded = expression(naics %in% c("491", "814")),
  low_pay = expression(gpay_firm < 1.25e6),
  rates = read_csv(
  "nyc, lower, rate
  TRUE, 0, 0.0011
  TRUE, 1.5e6, 0.0023
  TRUE, 1.75e6, 0.006
  FALSE, 0, 0.0011
  FALSE, 1.5e6, 0.0023
  FALSE, 1.75e6, 0.0034
  ") |> 
  mutate(upper = lead(lower, default = Inf), .by=nyc),
  description = "PMT tax rules for 2024"
)
  

make_taxplan <- function(shortname = NULL, 
                         lower_nyc = NULL,
                         rates_nyc = NULL, 
                         lower_burbs = NULL, 
                         rates_burbs = NULL, 
                         exempt = NULL,
                         excluded = NULL,
                         low_pay = NULL,
                         description = NULL){
  taxplan <- tax2024
  if(shortname == "tax2024") return(tax2024)
  
  taxplan$shortname <- shortname
  taxplan$description <- ifelse(is.null(description), shortname, description)
  
  if(!is.null(exempt)) taxplan$exempt <- expression(exempt)
  if(!is.null(excluded)) taxplan$excluded <- expression(excluded)
  if(!is.null(low_pay)) taxplan$low_pay <- expression(low_pay)
  
  if(!is.null(rates_nyc)){
      nyc <- tibble(nyc=rep(TRUE, length(rates_nyc)),
                    lower = lower_nyc,
                    rate = rates_nyc)|> 
        mutate(upper = lead(lower, default = Inf))
      taxplan$rates <- taxplan$rates |> 
        filter(!nyc) |> 
        bind_rows(nyc)
  }
  
  if(!is.null(rates_burbs)){
      burbs <- tibble(nyc=rep(FALSE, length(rates_burbs)),
                      lower = lower_burbs,
                      rate = rates_burbs)|> 
        mutate(upper = lead(lower, default = Inf))
      taxplan$rates <- taxplan$rates |> 
        filter(nyc) |> 
        bind_rows(burbs)
  }  
  
  return(taxplan)
}
# a <- str2expression("5 < 10")
# eval(a)

```

```{r}
#| label: function-tax-calculation
#| output: false

calc_tax <- function(data, taxplan){
  df <- data |>
    mutate(
      shortname = taxplan$shortname,
      exempt = eval(taxplan$exempt),
      excluded = eval(taxplan$excluded),
      low_pay = eval(taxplan$low_pay)) |> 
    left_join(taxplan$rates, 
              by = join_by(nyc, gpay_firm > lower, gpay_firm <= upper)) |> 
    select(-lower, -upper) |> 
    mutate(rate = ifelse(exempt | excluded | low_pay,
                        0,
                        rate),
           tax = rate * gpayroll)
  
  return(df)
}

```

```{r}
#| label: get-data
#| output: false

pmtdb <- readRDS(fs::path(PDINTERMEDIATE, "pmtdb_calibrated.rds"))
glimpse(pmtdb)
summary(pmtdb)

```

## DOB option: Raise top rate by 50bp on firms with payroll \>= \$10 million

-   Raise top PMT rate by 50 basis points on firms with payroll \>= \$10 million
-   No change for firms with lower payroll

```{r}
#| label: problem-setup
#| output: false

plan2024 <- make_taxplan("tax2024")

plandob <- make_taxplan("dob10m", 
             lower_nyc = c(0, 1.5e6, 1.75e6, 10e6),
             rates_nyc = c(0.0011, 0.0023, 0.006, 0.011),
             lower_burbs = c(0, 1.5e6, 1.75e6, 10e6),
             rates_burbs = c(0.0011, 0.0023, 0.0034, 0.0084),
             description = "DOB rate increase for payroll >= $10m")


prob <- list()
prob$year <- 2025
prob$emp_growth <- .015
prob$avg_wagerate_growth <- .04
prob$plan1 <- plan2024
prob$plan2 <- plandob

prob

# prob$emp_growth <- 0
# prob$avg_wagerate_growth <- 0

```

### Summary results

```{r}
#| label: tax-calc
#| output: false

pmtfc <- pmtdb_forecast(prob, pmtdb)
summary(pmtfc)

taxcomp <- bind_rows(
  pmtfc |> 
    mutate(calc_tax(pick(everything()), prob$plan1)) |> 
    mutate(basealt = "basetax"),
  pmtfc |> 
    mutate(calc_tax(pick(everything()), prob$plan2)) |> 
    mutate(basealt = "alttax"))

glimpse(taxcomp)
count(taxcomp, shortname)

taxcomp |> 
  summarise(tax=sum(tax),
            .by=c(ownerf, owner, shortname)) |> 
  pivot_wider(names_from = shortname,
              values_from = tax) |> 
  adorn_totals() |> 
  mutate(diff = dob10m - tax2024)

```

```{r}
#| label: show-dob-results
#| output: true

tabdata <- taxcomp |> 
  summarise(gpayroll = sum(gpayroll),
            tax=sum(tax),
            .by=c(ownerf, owner, basealt)) |> 
  pivot_wider(names_from = basealt,
              values_from = tax) |> 
  select(ownerf, owner, gpayroll, basetax, alttax) |> 
  arrange(ownerf) |> 
  adorn_totals() |> 
  mutate(change = alttax - basetax)

tabdata |> 
  gt() |> 
  tab_header(md("50bp PMT increase for **firms** with payroll > $10m, NYC+Suburbs combined"),
             subtitle="$ millions, 2025 levels") |> 
  fmt_number(columns = -c(ownerf, owner),
             scale = 1e-6,
             decimals = 0) |> 
  fmt_currency(columns = -c(ownerf, owner),
               rows = c(1, nrow(tabdata)),
               scale = 1e-6,
               decimals = 0)

```

### Results broken down by NYC and suburbs

```{r}
#| label: show-dob-geographic-details
#| output: true

tabdata <- taxcomp |> 
  summarise(tax=sum(tax),
            .by=c(nyc, ownerf, owner, basealt)) |> 
  mutate(nyc=ifelse(nyc, "nyc", "suburbs")) |> 
  pivot_wider(names_from = basealt,
              values_from = tax) |> 
  mutate(change = alttax - basetax) |> 
  pivot_wider(names_from = nyc,
              values_from = c(basetax, alttax, change)) |> 
  arrange(ownerf) |> 
  adorn_totals() |> 
  mutate(base_total = basetax_nyc + basetax_suburbs,
         alt_total = alttax_nyc + alttax_suburbs,
         change_total = change_nyc + change_suburbs,
         nyc_change_pct=change_nyc / change_total) |> 
  relocate(base_total, .after = basetax_suburbs) |> 
  relocate(alt_total, .after = alttax_suburbs)
# tabdata

tabdata |> 
  gt() |> 
  tab_header(md("50bp PMT increase for **firms** with payroll > $10m"),
             subtitle="$ millions, 2025 levels") |> 
  fmt_number(columns = -c(ownerf, owner,nyc_change_pct),
             scale = 1e-6,
             decimals = 0) |> 
  fmt_currency(columns = -c(ownerf, owner,nyc_change_pct),
               rows = c(1, nrow(tabdata)),
               scale = 1e-6,
               decimals = 0) |> 
  fmt_percent(columns=nyc_change_pct,
              decimals = 1) |> 
  sub_missing(missing_text = "--")

```

### Plan 1 (2024 law) and Plan 2 (DOB option) details

```{r}
#| label: show-plans
#| output: true

prob

```

```{r}
#| label: cleanup
rm(list = ls())
```

```{r stop_here, echo=FALSE}
knitr::knit_exit()
```
