project:
  type: book
  output-dir: _web
  
execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes
  
# rm _book/bill_outline.html; quarto render bill_outline.qmd  

book:
  title: "MTA PMT Analysis"
  subtitle: ""
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - part: "PMT rules"
      chapters:    
      - pmt_rules.qmd
    - part: "Prepare data"
      chapters:
      - method_steps.qmd
      # - get_cbp_data.qmd
      - get_susb_data.qmd    
      - get_qcew_data.qmd
      - clean_qcew_save_mta_subset.qmd
      - fillin_qcew.qmd
      # - employer_size.qmd
      # - make_pmt_base.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: 5
    toc-depth: 5
    toc-expand: false
    # css: styles.css
  # pdf:
  #   documentclass: scrreprt

# editor: console or visual

editor_options:
  chunk_output_type: console

# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt 