---
output: html_document
editor_options:
  chunk_output_type: console
---

# Wage growth in the MTA region since 2020 -- examine recessions

```{r}
#| label: setup
#| output: false

DMAIN <- here::here("pmt_database")


libs <- function(){
  source(fs::path(DMAIN, "R", "libraries.r"))
  source(fs::path(DMAIN, "R", "libraries_ts.r"))
}

suppressPackageStartupMessages(libs())
  
source(fs::path(DMAIN, "R", "constants.r"))
source(fs::path(DMAIN, "R", "functions.r"))

qmta <- readRDS(fs::path(PDINTERMEDIATE, "qcewstco.rds")) |> filter(mta)
# glimpse(qmta)
# count(qmta, ownerf, owner)


```

## Wage growth in the MTA region

```{r}
#| label: wage-growth
#| output: true

qmta |> 
  filter(naics=="00", owner== "Total Private and Government") |> 
  mutate(group=ifelse(nyc, "nyc", "suburbs")) |> 
  summarise(wages = sum(totwage), .by=c(group, year)) |> 
  pivot_wider(names_from = group, values_from = wages) |> 
  mutate(total = nyc + suburbs) |> 
  arrange(year) |> 
  mutate(across(c(nyc, suburbs, total), list(pct = \(x) x / lag(x) - 1))) |> 
  gt() |> 
  tab_header("Calendar year QCEW wages in the MTA region, $ millions") |> 
  fmt_number(columns = c(nyc, suburbs, total),
             scale = 1e-6, decimals = 0) |> 
  fmt_percent(columns = contains("pct"),
              decimals = 1)

```

## Recessions

```{r}
#| label: recessions
#| output: true

library(bdata)
recessions |> 
  select(-contains("decimal")) |> 
  gt()

```
