---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Creating the PMT database

## Overview

Create a database calibrated to the most recent data year (2024) with summary records for \# of firms, \# of establishments, \# of employees, payroll (and average payroll per firm, establishment, and employee) for the MTA region broken down by:

-   county (with the 5 counties of NYC as separate counties)
-   3-digit NAICS industry
-   establishment size

Thus, the data has slightly less than 9k records:

12 counties x \~80 industries on average x 9 size classes = 8.6k records

The data are "atomistic" in the sense that there are are no subotal records -- every record is a detail record. The records sum to totals. There are no subtotal records in the database

Calibrate the data to hit known QCEW totals for wages, establishments, and employment by county and industry. Ensure that sums across establishment-sizes add to QCEW totals (e.g., the sum of \# establishments, \# employees, and total payroll across the 9 establishment size groups for a county equal the QCEW total).

Do not forecast the database beyond the latest year in this project. That is a separate step we do while modeling.

## Data sources

-   Use QCEW data for wage, establishment, and employment control totals.

-   Use CBP data to allocate the QCEW data to establishment size groups

-   Use SUSB data to graft information about firms to the data file

-   **Quarterly Census of Employment and Wages (QCEW)** -- high-quality quarterly data \# establishments, employment, and wages by county, industry, and year. These are the totals we want to control to, before forecasting. Unfortunately, they are not available by establishment size or payroll size. Latest year is 2023.

-   **County Business Patterns (CBP)** -- has \# establishments, employment, and payroll by by establishment size. Used to apportion the QCEW data to establishment sizes, while still hitting all the QCEW totals. Latest year is 2022.

-   [**Statistics of United States Businesses (SUSB)**](https://www.census.gov/programs-surveys/susb.html) -- has \# of firms

## Prepare input data

-   QCEW -- get NY state and county records, put NYC and MTA markers on file, save as qcewstco.rds
-   CBP --

```{r stop_here, echo=FALSE}
knitr::knit_exit()
```

**pmt_final.rds** -- created in simple_estabs_basis.qmd (earlier version created in create_pmt_file.qmd)

-   simple_estabs_basis.qmd
    -   get **qcewstco.rds** (created in get_qcew_data.qmd)

    -   create **uqmta.rds** unique (atomistic); check oddballs

    -   apportion to estab sizes:

        -   get **cbpny.rds** (created in get_cbp_data_2025version.rds), create **ucbp.rds**

        -   create cbp qcew xwalk, save as qcxwalk.rds

        -   match uqmta, ucbp, xwalk

        -   save as **qcwide.rds**

        -   replace some bad recs (revisit)

        -   make long file

        -   optimize (which one??) save **qcew_cbp_opt_results.rds**

        -   adjust whien \< 0.5 or 1

        -   check sums
