project:
  type: book
  output-dir: _docs

execute:
  eval: true
  echo: true
  output: true
  freeze: auto
  
editor_options:
  chunk_output_type: console

format:
  html:
    theme: cosmo
    fig-width: 8
    fig-height: 8
    code-fold: true
  # pdf:
  #   documentclass: scrreprt

book:
  title: "Internet Marketplace Analysis"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - revenue_impact.qmd
    - background.qmd
    # - part: "Data preparation"
    #   chapters:
    #     - simple_forecast.qmd
        # - get_and_clean_tax_data.qmd
        # - get_and_clean_economic_data.qmd


bibliography: references.bib

# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt


# bibliography: _baseline.bib
# nocite: |
#   @*
