# Background

New York's sales tax revenue has benefited from two significant changes related to the internet that were implemented in 2019: (1) The state's response to the June 2018 *Wayfair* decision, and (2) the Internet Marketplace Act adopted with the state 2019-2020 budget. The latter is our primary interest, but to understand that we also need to understand *Wayfair*.

## Wayfair

Prior to the June 2018 U.S. Supreme Court decision in *South Dakota v. Wayfair*, states generally were not allowed to require vendors to collect sales tax owed on transactions unless the vendor had a physical presence in the state.

This situation is common with internet transactions and before that, with catalog sales. For example, if a New York consumer bought a jacket from Lands' End and -- positing that Lands' End does not have a physical presence in New York -- the state could not require Lands End to collect the sales tax. (Tax would be owed by the consumer, but it is not generally practical to force the consumer to pay tax in such a case.)

*Wayfair* changed this, allowing NY and other states to require the out-of-state vendor to collect tax when the economic connection to the state is sufficiently strong, based, for example, on the quantity or frequency of sales in a state. In other words, if the vendor has sufficient "economic nexus" with the state it can be required to collect sales tax owed. This does not establish new taxes, but rather just affects collection requirements. (The Supreme Court allowed South Dakota's law, which established economic nexus and collection requirements for retailers with \$100,000 or more of sales or 200 or more transactions in the state.)

New York already had dormant statutory language enacted in 1989 that defined a vendor as "A person who regularly or systematically solicits business in this state by the distribution, without regard to the location from which such distribution originated... to persons in this state and by reason thereof makes sales to persons within the state of tangible personal property, the use of which is taxed by this article, *if such solicitation satisfies the nexus requirement of the United States constitution*". (NYS Tax Law section 1101(b)(8)(E)))

Thus, *Wayfair* did not necessarily require a legislative response, but as a practical matter it required at least an administrative response to announce economic nexus rules. New York was slow to respond. (See for example, [this](https://www.thetaxadviser.com/issues/2019/jun/new-york-response-wayfair.html), and [this](https://www.hodgsonruss.com/media/publication/2573_2019stn6-5%20Feb.pdf).) On January 15, 2019 the State Tax Department issued *Important Notice N-19-1: Notice Regarding Sales Tax Registration Requirement for Businesses with No Physical Presence in New York State*, which informed vendors with no physical presence that they must register to collect sales tax if they meet New York's thresholds. The notice created some confusion among practitioners but appears to be retroactive, perhaps to June 2018.

This raises the question of when vendors would be registered and when revenue would appear in sales tax collections. Arguably, a small amount of revenue might be reported for the December-February 2019 sales tax quarter, more for the March-May 2019 sales tax quarter, and more still for the June-August 2019 quarter. It is something to be on the lookout for, because the last of these periods overlaps with the Internet Marketplace Act.

## Internet Marketplace Act

With adoption of the 2019-2020 budget, New York's tax law was "amended to require marketplace providers to collect sales tax on taxable sales of tangible personal property that they *facilitate* for marketplace sellers. These amendments apply to sales made on or after June 1, 2019." [Tax Department memo, *Sales Tax Collection Requirement for Marketplace Providers*.](https://www.tax.ny.gov/pdf/memos/sales/m19-2-1s.pdf) This change did not expand the sales tax, but rather created another mechanism for collection of existing liabilities.[see @governorkathyhochulNewYorkState2022]

In addition, the State will now require internet marketplace providers to collect sales taxes from third-party sellers that use their platforms. To help the MTA fund its 2020-2024 and successor capital programs, the **Enacted Budget requires the City to direct a portion of its sales tax collections to the MTA (\$127.5 million in SFY 2019-20 reflecting the portion of the year in which it is effective, \$170 million in SFY 2020-21, and increasing by one percent per year thereafter).** The City estimates that it will receive \$170 million annually from the additional internet sales tax but this will be offset by the City's required sales tax payment to the MTA. ([OSC](https://www.osc.state.ny.us/files/reports/budget/pdf/budget-enacted-2019-20.pdf); S.1509-C / A.2009-C, Chapter 59 of the Laws of 2019; also see [NYC IBO](https://ibo.nyc.ny.us/iboreports/recession-ahead-while-concerns-mount-projections-show-moderate-growth-in-nyc-tax-revenue-for-the-upcoming-years-may-2019.pdf).)
