project:
  type: website

website:
  title: "Links to MTA revenue analysis"
  navbar:
    background: white
    left:
      - text: "Home"
        href: index.qmd
format:
  html:
    theme: cosmo
    toc: true

# ```{r stop_here, echo=FALSE}
# knitr::knit_exit()
# ```
