project:
  type: website

website:
  title: "Links to MTA revenue analysis"
  navbar:
    background: white
    left:
      - text: "Home"
        href: index.qmd
format:
  html:
    theme: cosmo
    toc: true

# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt 

# ```{r stop_here, echo=FALSE}
# knitr::knit_exit()
# ```
