---
editor_options:
  chunk_output_type: console
---

# MTA Share of state PIT

```{r}
#| label: setup
#| output: false

library(tidyverse)
library(readxl)
library(vroom)
library(fs)
library(btools)
library(bggtools)
library(gt)

tprint <- 75  # default tibble print
options(tibble.print_max = tprint, tibble.print_min = tprint) # show up to tprint rows

ddir <- here::here("data")

```

```{r}
#| label: notes

# pit1 no agi ranges ----
# pit2 15 ranges, top $1m+; counties ----
# pit3 27 ranges, top $10m+; statewide ----
# pit4 8 income ranges, top $200k+; counties ----
# 
# Personal Income Tax Filers, Files Beginning Tax Year 2015, Summary Datasets
# Dataset 1 - Major Items by Liability Status and Place of Residence
# Dataset 2 - Major Items and Income & Deduction Components by Place of Residence and Broad Income Range
# Dataset 3 - Statewide Major Items and Income & Deduction Components by Liability Status and Detail Income Range
# Dataset 4 - County-level Major Items and Income & Deduction Components by Wide Income Range


```

Get previously saved PIT data.

```{r}
#| output: false
#| eval: false


# pit1 has no y, restype, por
pit1 <- readRDS(fs::path(ddir, "pit1.rds"))
# pit2 has mid y, restype, por, rrpet gain & loss, tax credits, other NYadds, taxes paid
pit2 <- readRDS(fs::path(ddir, "pit2.rds")) 
# pit3 has fine y, restype, tax creds, rrpet gain loss
pit3 <- readRDS(fs::path(ddir, "pit3.rds")) 
# pit4 has broad y, restype, por, 
pit4 <- readRDS(fs::path(ddir, "pit4.rds")) 

```

```{r}
#| eval: true

# pit2 has mid y, restype, por, rrpet gain & loss, tax credits, other NYadds, taxes paid
pit2 <- readRDS(fs::path(ddir, "pit2.rds")) 

# places
mtaxnyc <- c("Nassau", "Suffolk", "Dutchess", "Orange", "Putnam", "Rockland", "Westchester")
nyc <- "All New York City"
nycos <- c("Bronx", "Kings", "Manhattan", "Queens", "Richmond")

glimpse(pit2)
vnames2 <- tibble(varnum=1:ncol(pit2), vname=colnames(pit2))

# vnames3 <- tibble(varnum=1:ncol(pit3), vname=colnames(pit3))

```

# Examine shares of NYS PIT using 2019 tax data

2020 was disturbed by COVID and 2021 and 2022 are disrupted by the PTET.

```{r}
#| eval: true

pit2a <- pit2 |> 
  select(taxyear=1, resstat=2,
         por=3, county=4, state=5, country=6,
         nyagirange=7, nret=9, ti=17, taxbc=18, taxac=20, porsort=54, ysort=55)

count(pit2a, ysort, nyagirange)

asort <- c("nyc", "nycos", "mtaxnyc", "mtatotal", "resxmta", "restotal", "nrpy", "grandtotal")

pit2b <- pit2a |> 
  filter(taxyear==2019, ysort==16) |> 
  mutate(
    atype = case_when(
      resstat == "Full-Year Resident" & por %in% mtaxnyc ~ "mtaxnyc",
      resstat == "Full-Year Resident" & por == nyc ~ "nyc",
      resstat == "Full-Year Resident" & county %in% nycos ~ "nycos",
      resstat == "Full-Year Resident" & por == "All Places" ~ "restotal",
      resstat == "Full-Year Resident" & porsort == 70 ~ "res_subtotal",
      resstat == "Full-Year Resident" ~ "resxmta",
      resstat == "Full-Year Nonresident" & por == "All Places" ~ "nrpy",
      resstat == "Full-Year Nonresident" ~ "nonres_detail",
      resstat == "Part-Year Resident" & por == "All Places" ~ "nrpy",
      resstat == "All Filers" & por == "All Places" ~ "grandtotal",
      .default = NA_character_)
    ) |> 
  filter(!atype %in% c("res_subtotal", "nonres_detail")) |> 
  mutate(area = ifelse(atype == "mtaxnyc", county, atype)) |> 
  filter(!is.na(area)) |> 
  summarise(taxbc = sum(taxbc), taxac = sum(taxac), .by=c(atype, area)) |> 
  mutate(asort = factor(atype, asort) |> as.integer()) |> 
  relocate(asort) |> 
  arrange(asort, area)

# create mta total and mta + nonresidents and get sort and level
pit2b # check totals -- good

mtatotal <- pit2b |> 
  filter(atype %in% c("nyc", "mtaxnyc")) |> 
  summarise(taxbc = sum(taxbc), taxac = sum(taxac)) |> 
  mutate(atype = "mtatotal", area = "mtatotal")

mtanonres <- pit2b |> 
  filter(atype %in% c("nyc", "mtaxnyc", "nrpy")) |> 
  summarise(taxbc = sum(taxbc), taxac = sum(taxac)) |> 
  mutate(atype = "mtanonres", area = "mtanonres")

pit2c <- pit2b |> 
  filter(!atype %in% c("nycos")) |> 
  select(-asort) |> 
  bind_rows(mtatotal, mtanonres)
pit2c

```

```{r}
#| label: show-shares
#| eval: true
#| output: true

asort3 <- c("nyc", "mtaxnyc", "mtatotal", "resxmta", "restotal", "nrpy", "grandtotal", "mtanonres")

tabdata <- pit2c |> 
  select(atype, area, taxac) |> 
  mutate(asort=factor(atype, levels=asort3)) |> 
  relocate(asort) |> 
  arrange(asort, area) |> 
  mutate(pctgrand=taxac / taxac[area=="grandtotal"],
         pctres=taxac / taxac[area=="restotal"],
         pctres=ifelse(atype %in% c("nrpy", "grandtotal", "mtanonres"),
                       NA_real_,
                       pctres),
         area=case_when(
           area == "nyc" ~ "New York City",
           asort == "mtaxnyc" ~ area,
           area == "mtatotal" ~ "MTA Total",
           atype == "resxmta" ~ "NYS outside MTA region",
           atype == "restotal" ~ "NYS resident total",
           atype == "nrpy" ~ "Non-resident & part-year resident",
           atype == "grandtotal" ~ "Grand total",
           atype == "mtanonres" ~ "MEMO: MTA plus nonresidents",
           .default = "ERROR"))


tab <- tabdata |> 
  select(-c(asort, atype)) |> 
  gt() |> 
  tab_header("MTA and other areas' share of NYS Personal Income Tax, 2019") |> 
  cols_label(area = "Area",
             taxac = "Tax liability after credits ($ millions)",
             pctgrand = "% of grand total",
             pctres = "% of resident total") |> 
  fmt_number(columns=taxac,
             scale_by = 1e-6,
             decimals = 0) |> 
  fmt_percent(columns = c(pctgrand, pctres),
              decimals = 1) |> 
  sub_missing(missing_text = "--")
tab

```

```{r stop_here, echo=FALSE}
knitr::knit_exit()
```

```{r}

# 2022 data

glimpse(pit2)
vnames2

pit2a <- pit2 |> 
  select(taxyear=1, resstat=2,
         por=3, county=4, state=5, country=6,
         nyagirange=7, nret=9, ti=17, taxbc=18, taxac=20, porsort=54, ysort=55)

count(pit2a, ysort, nyagirange)

asort <- c("nyc", "nycos", "mtaxnyc", "mtatotal", "resxmta", "restotal", "nrpy", "grandtotal")

pit2b <- pit2a |> 
  filter(taxyear==2022, ysort==16) |> 
  mutate(
    atype = case_when(
      resstat == "Full-Year Resident" & por %in% mtaxnyc ~ "mtaxnyc",
      resstat == "Full-Year Resident" & por == nyc ~ "nyc",
      resstat == "Full-Year Resident" & county %in% nycos ~ "nycos",
      resstat == "Full-Year Resident" & por == "All Places" ~ "restotal",
      resstat == "Full-Year Resident" & porsort == 70 ~ "res_subtotal",
      resstat == "Full-Year Resident" ~ "resxmta",
      resstat == "Full-Year Nonresident" & por == "All Places" ~ "nrpy",
      resstat == "Full-Year Nonresident" ~ "nonres_detail",
      resstat == "Part-Year Resident" & por == "All Places" ~ "nrpy",
      resstat == "All Filers" & por == "All Places" ~ "grandtotal",
      .default = NA_character_)
    ) |> 
  filter(!atype %in% c("res_subtotal", "nonres_detail")) |> 
  mutate(area = ifelse(atype == "mtaxnyc", county, atype)) |> 
  filter(!is.na(area)) |> 
  summarise(taxbc = sum(taxbc), taxac = sum(taxac), .by=c(atype, area)) |> 
  mutate(asort = factor(atype, asort) |> as.integer()) |> 
  relocate(asort) |> 
  arrange(asort, area)

# create mta total and mta + nonresidents and get sort and level
pit2b # check totals -- good

mtatotal <- pit2b |> 
  filter(atype %in% c("nyc", "mtaxnyc")) |> 
  summarise(taxac = sum(taxac)) |> 
  mutate(atype = "mtatotal", area = "mtatotal")

mtanonres <- pit2b |> 
  filter(atype %in% c("nyc", "mtaxnyc", "nrpy")) |> 
  summarise(taxac = sum(taxac)) |> 
  mutate(atype = "mtanonres", area = "mtanonres")

asort2 <- c("nyc", "mtaxnyc", "mtatotal", "nrpy", "mtanonres", "resxmta", "grandtotal")

pit2c <- pit2b |> 
  filter(!atype %in% c("nycos", "restotal")) |> 
  select(-asort) |> 
  bind_rows(mtatotal, mtanonres) |> 
  mutate(asort = factor(atype, asort2) |> as.integer()) |> 
  relocate(asort) |> 
  arrange(asort, area)
pit2c



```

```{r}
# nonresident check

nonrescheck <- pit2a |> 
  filter(ysort==16, resstat == "Full-Year Nonresident", por == "All Places") |> 
  arrange(taxyear)
nonrescheck
# HUGE jump in taxbc in 2021 but not in taxac (taxac)
# 
vnames3

pit3a <- pit3 |> 
  select(taxyear=1, taxstatus=2, resstat=3, nyagirange=4,
         nret=6,
         fednyagi=11, nyagi=12, nyti=21, 
         taxbc=22, credits=23, taxac=24,
         statsort=88, ysort=89)

pit3b <- pit3a |> 
  filter(ysort==28)

pit3b |> 
  filter(taxyear %in% 2015:2022) |> 
  select(-c(nyagirange, ysort)) |> 
  arrange(taxstatus, resstat, taxyear) |> 
  write_csv(fs::path(ddir, "pit3_summary.csv"))

```
